### ISSUE TITLE
Consider adding an open source license?

### ISSUE THREAD

**Issue by tomsing1** [hawkjo/freebarcodes#4]
Thanks a lot for making these algorithms available to the research community! I noticed that you listed `Freely distributable` in the `setup.py` file, but I don't think you specified any open source license. 

Perhaps you would consider adding an explicit license to the repository, e.g. the [MIT license](https://opensource.org/licenses/MIT) or similar? 

That might be helpful, because according to this [github help page](https://help.github.com/en/articles/licensing-a-repository) 
> For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

https://github.com/hawkjo/freebarcodes/blob/d96d01f99313e7c142152c93a0e8aa44cfa0badb/setup.py#L27

Many thanks for considering this suggestion!

**Comment by hawkjo** [comment]
Thank you for you feedback. I'll look into it.
